"""empty message

Revision ID: 00935ddadb2a
Revises: 7c4de11d0bfc
Create Date: 2019-05-26 22:06:59.221121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00935ddadb2a'
down_revision = '7c4de11d0bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testset', 'full_score',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               server_default='0',
               existing_nullable=False)
    op.alter_column('user', 'is_teacher',
               existing_type=mysql.TINYINT(display_width=1),
               server_default='0',
               existing_nullable=False)
    op.alter_column('submission', 'is_solution',
               existing_type=mysql.TINYINT(display_width=1),
               server_default='0',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'is_solution',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'is_teacher',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('testset', 'full_score',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               server_default=sa.text("'0.00'"),
               existing_nullable=False)
    # ### end Alembic commands ###
