"""empty message

Revision ID: 3636872b7876
Revises: a13d0ed4bfd2
Create Date: 2019-05-23 14:16:03.078313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3636872b7876'
down_revision = 'a13d0ed4bfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_for_usergroup',
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['user_group.gid'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('gid', 'task_id')
    )
    op.create_table('submission_in_task',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['submission.sid'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('sid', 'task_id')
    )
    op.drop_table('task_for_user_group')
    op.drop_constraint('submission_ibfk_4', 'submission', type_='foreignkey')
    op.drop_column('submission', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('submission_ibfk_4', 'submission', 'task', ['task_id'], ['task_id'])
    op.create_table('task_for_user_group',
    sa.Column('gid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['user_group.gid'], name='task_for_user_group_ibfk_1'),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], name='task_for_user_group_ibfk_2'),
    sa.PrimaryKeyConstraint('gid', 'task_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('submission_in_task')
    op.drop_table('task_for_usergroup')
    # ### end Alembic commands ###
