"""empty message

Revision ID: 497c20958faf
Revises: a7c3c232ea10
Create Date: 2019-05-04 13:24:43.374826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497c20958faf'
down_revision = 'a7c3c232ea10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Problem',
    sa.Column('pID', sa.Integer(), nullable=False),
    sa.Column('level', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('pID')
    )
    op.create_table('Submission',
    sa.Column('sID', sa.Integer(), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('isSolution', sa.Boolean(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('dateAndTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Submission')
    op.drop_table('Problem')
    # ### end Alembic commands ###
