"""empty message

Revision ID: 4fe14ebd5726
Revises: e88bea3b90dd
Create Date: 2019-05-03 13:59:39.400927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fe14ebd5726'
down_revision = 'e88bea3b90dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserGroup',
    sa.Column('gid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_table('UserInGroup',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['UserGroup.gid'], ),
    sa.ForeignKeyConstraint(['uid'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'gid')
    )
    op.add_column('User', sa.Column('is_teacher', sa.Boolean(), nullable=False))
    op.drop_column('User', 'isTeacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('isTeacher', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('User', 'is_teacher')
    op.drop_table('UserInGroup')
    op.drop_table('UserGroup')
    # ### end Alembic commands ###
