"""empty message

Revision ID: 551f047e7d18
Revises: b685f84b1bac
Create Date: 2019-05-04 21:54:37.353791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '551f047e7d18'
down_revision = 'b685f84b1bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'score',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'score',
               existing_type=sa.Text(),
               type_=mysql.DECIMAL(precision=6, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
