"""empty message

Revision ID: 629234576fb8
Revises: d65619966782
Create Date: 2019-05-18 21:29:09.713987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '629234576fb8'
down_revision = 'd65619966782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=256), nullable=True))
    op.drop_column('user', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
