"""empty message

Revision ID: 7c4de11d0bfc
Revises: 3636872b7876
Create Date: 2019-05-23 14:41:51.748367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c4de11d0bfc'
down_revision = '3636872b7876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('announcement', sa.Column('publish_time', sa.DateTime(), nullable=False))
    # op.drop_column('announcement', 'date_time')
    op.alter_column('announcement', 'date_time', new_column_name = 'publish_time', existing_type = sa.DateTime(), existing_nullable = False)
    # op.add_column('submission', sa.Column('submit_time', sa.DateTime(), nullable=False))
    # op.drop_column('submission', 'date_time')
    op.alter_column('submission', 'date_time', new_column_name = 'submit_time', existing_type = sa.DateTime(), existing_nullable = False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('submission', sa.Column('date_time', mysql.DATETIME(), nullable=False))
    # op.drop_column('submission', 'submit_time')
    op.alter_column('announcement', 'publish_time', new_column_name = 'date_time', existing_type = sa.DateTime(), existing_nullable = False)
    # op.add_column('announcement', sa.Column('date_time', mysql.DATETIME(), nullable=False))
    # op.drop_column('announcement', 'publish_time')
    op.alter_column('submission', 'submit_time', new_column_name = 'date_time', existing_type = sa.DateTime(), existing_nullable = False)
    # ### end Alembic commands ###
