"""empty message

Revision ID: 7f7c13f10d11
Revises: 
Create Date: 2019-05-04 16:30:46.710429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7c13f10d11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_teacher', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('user_group',
    sa.Column('gid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_table('submission',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('is_solution', sa.Boolean(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['problem.pid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('user_in_group',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['user_group.gid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'gid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_in_group')
    op.drop_table('submission')
    op.drop_table('user_group')
    op.drop_table('user')
    op.drop_table('problem')
    # ### end Alembic commands ###
