"""empty message

Revision ID: 80840c1050ba
Revises: 0e31b3251fe7
Create Date: 2019-05-18 23:19:17.623162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80840c1050ba'
down_revision = '0e31b3251fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('visible', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'visible')
    # ### end Alembic commands ###
