"""empty message

Revision ID: 83935c1432e9
Revises: e0f3d9eed827
Create Date: 2019-05-19 13:40:57.046755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83935c1432e9'
down_revision = 'e0f3d9eed827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('item_per_page', sa.Integer(), server_default='20', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'item_per_page')
    # ### end Alembic commands ###
