"""empty message

Revision ID: 8c475eb11e86
Revises: 975083e2d041
Create Date: 2019-05-13 20:33:50.337308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c475eb11e86'
down_revision = '975083e2d041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tag', ['tag_name'])
    op.drop_constraint('user_in_group_ibfk_2', 'user_in_group', type_='foreignkey')
    op.create_foreign_key(None, 'user_in_group', 'user', ['uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_in_group', type_='foreignkey')
    op.create_foreign_key('user_in_group_ibfk_2', 'user_in_group', 'user', ['uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint(None, 'tag', type_='unique')
    # ### end Alembic commands ###
