"""empty message

Revision ID: 975083e2d041
Revises: e3b6f199e0e9
Create Date: 2019-05-12 14:51:56.740069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975083e2d041'
down_revision = 'e3b6f199e0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_in_group_ibfk_2', 'user_in_group', type_='foreignkey')
    op.create_foreign_key(None, 'user_in_group', 'user', ['uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_in_group', type_='foreignkey')
    op.create_foreign_key('user_in_group_ibfk_2', 'user_in_group', 'user', ['uid'], ['uid'])
    # ### end Alembic commands ###
