"""empty message

Revision ID: a13d0ed4bfd2
Revises: e41ad76a6ea9
Create Date: 2019-05-20 01:18:11.229701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a13d0ed4bfd2'
down_revision = 'e41ad76a6ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'full_score')
    op.add_column('testset', sa.Column('full_score', sa.DECIMAL(precision=6, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testset', 'full_score')
    op.add_column('submission', sa.Column('full_score', mysql.DECIMAL(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###
