"""empty message

Revision ID: a7c3c232ea10
Revises: 4fe14ebd5726
Create Date: 2019-05-03 14:36:24.499757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7c3c232ea10'
down_revision = '4fe14ebd5726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('User', sa.Column('user_name', sa.String(length=64), nullable=False))
    # op.drop_index('name', table_name='User')
    # op.create_unique_constraint(None, 'User', ['user_name'])
    # op.drop_column('User', 'name')
    op.alter_column(
        'User',
        'name',
        new_column_name = 'user_name',
        existing_type = sa.String(length=64),
        existing_nullable = False
    )
    op.drop_index('name', table_name='User')
    op.create_index('user_name', 'User', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('User', sa.Column('name', mysql.VARCHAR(length=64), nullable=False))
    # op.drop_constraint(None, 'User', type_='unique')
    # op.create_index('name', 'User', ['name'], unique=True)
    # op.drop_column('User', 'user_name')
    op.alter_column(
        'User',
        'user_name',
        new_column_name = 'name',
        existing_type = sa.String(length=64),
        existing_nullable = False
    )
    op.drop_index('user_name', table_name='User')
    op.create_index('name', 'User', ['name'], unique=True)
    # ### end Alembic commands ###
