"""empty message

Revision ID: b685f84b1bac
Revises: 7f7c13f10d11
Create Date: 2019-05-04 17:03:06.652783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b685f84b1bac'
down_revision = '7f7c13f10d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=64), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('test',
    sa.Column('test_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('testset',
    sa.Column('testset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('testset_id')
    )
    op.create_table('problem_in_task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['problem.pid'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('task_id', 'pid')
    )
    op.create_table('tag_of_problem',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['problem.pid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'pid')
    )
    op.create_table('test_in_testset',
    sa.Column('testset_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.test_id'], ),
    sa.ForeignKeyConstraint(['testset_id'], ['testset.testset_id'], ),
    sa.PrimaryKeyConstraint('testset_id', 'test_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_in_testset')
    op.drop_table('tag_of_problem')
    op.drop_table('problem_in_task')
    op.drop_table('testset')
    op.drop_table('test')
    op.drop_table('task')
    op.drop_table('tag')
    # ### end Alembic commands ###
