"""empty message

Revision ID: be2e70133e99
Revises: 551f047e7d18
Create Date: 2019-05-05 01:51:09.030470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be2e70133e99'
down_revision = '551f047e7d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('testset_id', sa.Integer(), nullable=True))
    op.alter_column('problem', 'level',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'problem', 'testset', ['testset_id'], ['testset_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.alter_column('problem', 'level',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=6, scale=2),
               existing_nullable=False)
    op.drop_column('problem', 'testset_id')
    # ### end Alembic commands ###
