"""empty message

Revision ID: cb362fb020f4
Revises: 80840c1050ba
Create Date: 2019-05-19 01:43:37.895993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb362fb020f4'
down_revision = '80840c1050ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('testset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'submission', 'testset', ['testset_id'], ['testset_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_column('submission', 'testset_id')
    # ### end Alembic commands ###
