"""empty message

Revision ID: e0f3d9eed827
Revises: 9d2704ae7566
Create Date: 2019-05-19 08:54:04.352373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0f3d9eed827'
down_revision = '9d2704ae7566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('result', sa.Text(), nullable=True))
    op.drop_column('submission', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('score', mysql.TEXT(), nullable=True))
    op.drop_column('submission', 'result')
    # ### end Alembic commands ###
