"""empty message

Revision ID: e3b6f199e0e9
Revises: be2e70133e99
Create Date: 2019-05-11 15:07:46.601493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b6f199e0e9'
down_revision = 'be2e70133e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_for_user_group',
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['user_group.gid'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('gid', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_for_user_group')
    # ### end Alembic commands ###
